import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "Terms of Service | PDA Your IEP",
    description: "Read the Terms of Service for using our AI-powered IEP analysis tool. Educational and informational use only.",
}

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen flex flex-col bg-[var(--wc-cream)]">
            <Navbar />
            <main className="flex-1 container mx-auto pt-32 pb-16 px-4 md:px-6 max-w-4xl">
                <div className="wc-card p-8 md:p-12">
                    <div className="mb-8 p-4 bg-[var(--wc-blue-pale)] border border-[var(--wc-blue)]/30 rounded-xl">
                        <p className="text-sm text-[var(--wc-blue-dark)] font-medium text-center">
                            Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                        </p>
                    </div>

                    <div className="prose prose-slate max-w-none prose-headings:text-[var(--wc-brown-darker)] prose-headings:font-display prose-p:text-[var(--wc-brown-dark)] prose-li:text-[var(--wc-brown-dark)] prose-strong:text-[var(--wc-brown-darker)]">
                        <h1 className="text-3xl md:text-4xl font-display font-bold tracking-tight text-[var(--wc-brown-darker)] mb-6">Terms of Service</h1>

                        <p className="lead text-lg text-[var(--wc-brown-dark)]">
                            Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the PDA Your IEP website (the "Service") operated by Kyle Wegner ("us", "we", or "our").
                        </p>

                        <h2>1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
                        </p>

                        <div className="p-6 bg-[var(--wc-gold-pale)] border border-[var(--wc-gold)]/50 rounded-xl my-8 not-prose">
                            <h3 className="text-lg font-display font-bold text-[var(--wc-gold-dark)] mb-2">2. Nature of the Service (Disclaimer)</h3>
                            <p className="text-[var(--wc-brown-dark)] text-sm leading-relaxed mb-4">
                                The Service is an AI-powered educational and communication tool. It is <strong className="text-[var(--wc-brown-darker)]">NOT</strong> a substitute for professional medical advice, diagnosis, or treatment.
                            </p>
                            <ul className="list-disc pl-5 space-y-2 text-sm text-[var(--wc-brown-dark)]">
                                <li>The content generated by this Service is for informational and educational purposes only.</li>
                                <li>We do not guarantee the accuracy, completeness, or usefulness of any translation, analysis, or rating provided by the AI.</li>
                                <li>Always seek the advice of your physician, psychologist, special education attorney, or other qualified professional with any questions you may have regarding a medical condition, legal right, or the care of a neurodivergent individual.</li>
                                <li>Reliance on any information provided by this Service is solely at your own risk.</li>
                            </ul>
                        </div>

                        <h2>3. Donations and Payments</h2>
                        <p>
                            The Service is provided free of charge. You may choose to support the developer through voluntary donations via Stripe ("Buy Me a Coffee").
                        </p>
                        <ul>
                            <li><strong>Voluntary Support:</strong> Payments made through the "Buy Me a Coffee" feature are voluntary donations to support the ongoing development and hosting costs of the project.</li>
                            <li><strong>No Goods or Services:</strong> A donation does not entitle you to any premium features, goods, services, or special treatment. It is a gift.</li>
                            <li><strong>Non-Refundable:</strong> All donations are final and non-refundable.</li>
                        </ul>

                        <h2>4. User Conduct</h2>
                        <p>You agree not to use the Service:</p>
                        <ul>
                            <li>In any way that violates any applicable national or international law or regulation.</li>
                            <li>To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail", "chain letter," "spam," or any other similar solicitation.</li>
                            <li>To attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Service or the servers on which it is hosted.</li>
                            <li>To reverse engineer the AI prompts or underlying technology of the Service.</li>
                        </ul>

                        <h2>5. Intellectual Property</h2>
                        <p>
                            The Service and its original content (excluding content provided by you), features, and functionality are and will remain the exclusive property of Kyle Wegner and his licensors.
                        </p>
                        <p>
                            <strong>Your Content:</strong> You retain all rights to the documents you upload. By uploading content, you grant us a license to process, analyze, and display that content solely for the purpose of providing the Service to you.
                        </p>

                        <h2>6. Limitation of Liability</h2>
                        <p>
                            In no event shall Kyle Wegner, nor his partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
                        </p>
                        <p>
                            Specifically, we are not liable for the outcome of any IEP meeting, due process hearing, or educational decision made based on information provided by this Service.
                        </p>

                        <h2>7. Changes</h2>
                        <p>
                            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
                        </p>

                        <h2>8. Contact Us</h2>
                        <p>
                            If you have any questions about these Terms, please contact us via our Support page.
                        </p>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    )
}
